In [4]:
import numpy as np
np.__version__

alist1 = [1,2,3,4,5,6,7]
print(alist1)
print(type(alist1))

[1, 2, 3, 4, 5, 6, 7]
<class 'list'>


In [6]:
ar1 = np.array(alist1)

print(ar1)
print(type(ar1))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [7]:
print(ar1.dtype)

int64


In [8]:
list_data = [1, 2.,3]

arr = np.array(list_data)

print(arr.dtype)

float64


In [10]:
arr1 = np.arange(1,11)

arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arr2)
print(arr2.ndim)
print(arr2.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [21]:
arr4 = arr2.reshape(2,-1)

print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
2
(2, 6)


In [22]:
arr1 = np.array([1,2,3,4])

print(arr1.ndim)
print(arr1.shape)

1
(4,)


In [23]:
arr3 = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]]])

print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [50]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

# print(arr.reshape(2,-1))
print(arr.reshape(2, 2, 3))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [47]:
alist = np.array([1,2,3,4,5])
blist = np.array([5,6,7,8,9])

print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)

[ 6  8 10 12 14]
[-4 -4 -4 -4 -4]
[ 5 12 21 32 45]
[0.2        0.33333333 0.42857143 0.5        0.55555556]


In [51]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [52]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
data = [0,1,2,3,4,5,6,7,8,9]

list(map((lambda x: x*2), data))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [60]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(2*a+b)
print(a == 2)
print(b > 10)
print((a==2) & (b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [63]:
c = np.array([[0,1,2],[3,4,5]])
c

len(c)
len(c[0])

3

In [72]:
d = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]], [[11,12,13,14],[15,16,17,18], [19,20,21,22]]])

print(d)
print(len(d))
print(len(d[0]))
print(len(d[0][0]))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
2
3
4


In [79]:
arr = np.array([1,2,3])
arr.shape

(3,)

In [81]:
c = np.array([[0,1,2], [3,4,5]])

c.shape


(2, 3)

In [82]:
a = np.array([0,1,2,3,4])
print(a[2])
print(a[-1])

2
4


In [86]:
a = np.array([[0,1,2], [2,3,4]])
print(*a[0][:2])
print(a[0,:3])

0 1
[0 1 2]


In [93]:
a[:,1]
a[1,1:]
a[:2,:2]

array([[0, 1],
       [2, 3]])

In [94]:
arr = np.array([10,20,30,40,50])
result = arr[[0,2,4]]
print(result)

[10 30 50]


In [98]:
a= np.array([0,1,2,3,4,5,6,7,8,9])

a[a%2==0]
a[::2]

array([0, 2, 4, 6, 8])

In [99]:
a = np.array([11,22,33,44,55,66,77,88,99])
idx = np.array([0,0,0,0,0,1,1,1,1,2,2,2,2,2])
a[idx]

array([11, 11, 11, 11, 11, 22, 22, 22, 22, 33, 33, 33, 33, 33])

In [122]:
a=np.array([[1,2,3,4], [4,5,6,7],[7,8,9,0]])
idx = np.array([0,-1])
a[:,idx]

array([[1, 4],
       [4, 7],
       [7, 0]])

In [125]:
a=np.array([[1,2,3,4], [4,5,6,7],[7,8,9,0]])
idx = np.array([2,0,1])
a[idx, :]

array([[7, 8, 9, 0],
       [1, 2, 3, 4],
       [4, 5, 6, 7]])

In [141]:
x = np.arange(21)

print(x[(x%3==0) & (x!=0)])
print(x[x%4==1])
print(x[(x%3==0) & (x%4==0)])


[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[ 0 12]


In [142]:
x = np.array([1,2,3.0])
x[0] + x[2]

np.float64(4.0)

In [143]:
a = np.arange(12)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
a.reshape(2,-1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [154]:
a.flatten
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [166]:
x = np.arange(1,10001)
y = np.arange(10001,20001)
z = np.zeros_like(x)

# z = x + y
for i in range(10000):
    z[i] = x[i] + y[i]

# z[:10]

array([10001, 10002, 10003, ..., 19998, 19999, 20000])

In [178]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

CPU times: total: 0 ns
Wall time: 4.88 ms


In [173]:
%time z = x+y

CPU times: total: 0 ns
Wall time: 0 ns


In [179]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

a == b
a >= b

array([False,  True,  True,  True])

In [180]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [181]:
print(x.sum())
print(x.min())
print(x.argmin()) #min의 위치
print(x.mean())

10
1
0
2.5


In [182]:
x= np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [184]:
x.sum()
x.sum(axis=0) #column

array([3, 3])

In [185]:
x.sum(axis=1) #row

array([2, 4])